---
:concurrency: <%= Integer(ENV.fetch('SIDEKIQ_CONCURRENCY', 5)) %>

staging:
  :concurrency: <%= Integer(ENV.fetch('SIDEKIQ_CONCURRENCY', 25)) %>

production:
  :concurrency: <%= Integer(ENV.fetch('SIDEKIQ_CONCURRENCY', 50)) %>

:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
